# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccstat < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atomiyama/ccstat/releases/download/v0.2.0/ccstat_Darwin_x86_64.tar.gz"
      sha256 "f8b7818c4eeb0d817a3dbc774c3e04f4d949cac9c3ca94dbf5538729e7bca1a4"

      def install
        bin.install "ccstat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atomiyama/ccstat/releases/download/v0.2.0/ccstat_Darwin_arm64.tar.gz"
      sha256 "632d957ea3888929cf85fd3e7159d59520c4484c49d18cfe7a36a06df0918310"

      def install
        bin.install "ccstat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atomiyama/ccstat/releases/download/v0.2.0/ccstat_Linux_arm64.tar.gz"
      sha256 "c168e630187ba4a6403680bb7df1b6deee36c5c18a935c75b1f2afb02cd2fd14"

      def install
        bin.install "ccstat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/atomiyama/ccstat/releases/download/v0.2.0/ccstat_Linux_x86_64.tar.gz"
      sha256 "61077a62e3f066b43456f2d0754c3bd65527143a900afd21fe31f42c242bdc92"

      def install
        bin.install "ccstat"
      end
    end
  end
end
